language: en
autodownload: true
installondownload: false
internet: true
senderrorreport: true
senddebugfile: true
debug: false
debugfile: true
UsePrefix: true
Prefix: Paypassage
PrefixColor: b
TextColor: 6
updateIntervall: 30