language: en
autodownload: true
installondownload: false
internet: true
senderrorreport: true
senddebugfile: true
debug: false
debugfile: true
users_can_choose_privacy: true
UsePrefix: true
Prefix: Paypassage
PrefixColor: b
TextColor: 6
updateIntervall: 30
sign_headline: Paypassage
maxTeleportDistance: 30
minPrice: 0
use_MySQL: false
dbPath: localhost:3306/Paypassage
dbUser: root
dbPassword: root